changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver:major
    - title: Features
      labels:
        - enhancement
        - feature
        - semver:minor
    - title: Bug Fixes
      labels:
        - bug
        - fix
        - semver:patch
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - ci
    - title: Other Changes
      labels:
        - "*"
