#!/usr/bin/env bun
import { homedir } from "node:os";
import { join } from "node:path";
import { appendFileSync, mkdirSync, readFileSync, existsSync } from "node:fs";
import { dirname } from "node:path";
import type { CanonicalEvent } from "../orch-monitor/lib/canonical-event.ts";
import { loadForwarderConfig } from "./lib/config.ts";
import { readCheckpoint, writeCheckpoint } from "./lib/checkpoint.ts";
import { createTailer } from "./lib/tail.ts";
import { log } from "./lib/logger.ts";
import { logDaemonHeartbeat } from "../lib/daemon-heartbeat.mjs";
import { getEventName } from "../lib/event-name.mjs"; // CTL-1834: THE shared event-name boundary
import { emitProcessMemoryMetric } from "../lib/process-memory-metric.mjs"; // CTL-1517: per-process RSS/heap gauge
import { OtlpSender } from "./lib/destinations/otlp.ts";
import { PosthogSender } from "./lib/destinations/posthog.ts";
import { CloudflareAESender } from "./lib/destinations/cloudflare-ae.ts";
import {
  isFlatEvent,
  normalizeFlatEvent,
  isPinoRecord,
  normalizePinoRecord,
} from "./lib/normalize.ts";
import { dlqDepth } from "./lib/dlq.ts";
import { buildCanonicalEnvelope } from "./lib/canonical.ts";
import { createSparseWarnGate } from "./lib/sparse-warn.ts";
import { configureDropSurface, evaluateDropSurface } from "./lib/drop-surface.ts";
import { eventLogBasenameFor, resolveRotationScheme } from "../lib/event-log-paths.mjs";

const CATALYST_DIR = process.env.CATALYST_DIR ?? join(homedir(), "catalyst");
const EVENTS_DIR = process.env.CATALYST_EVENTS_DIR ?? join(CATALYST_DIR, "events");
const CHECKPOINT_PATH = join(CATALYST_DIR, "otel-forward.checkpoint.json");
// CTL-1506 (Codex P1): the project key's authoritative source is Layer-1
// .catalyst/config.json (`catalyst.projectKey`), which links to the Layer-2
// config-{projectKey}.json. Resolve it in precedence order — CATALYST_PROJECT_KEY env
// override → Layer-1 key → default — so a non-default key works under the normal
// `catalyst-monitor.sh forward-start` path (which exports no env var). Absent/malformed
// Layer-1 file falls back safely to the default.
function findLayer1Config(): string | null {
  // CTL-1506 (Codex #2742 P1): resolve INDEPENDENTLY of the working directory first.
  // The supported service path has no meaningful cwd — the LaunchAgent generated by
  // catalyst-stack sets no WorkingDirectory and catalyst-monitor.sh forwards no
  // project/config override — so under launchd the ancestor walk below starts from
  // whatever launchd chose (typically /), finds nothing, and every non-default project
  // silently resolved to `catalyst-workspace` and loaded the WRONG Layer-2 file.
  //
  // Honor the repo's established pin, precedence CATALYST_CONFIG_FILE >
  // CATALYST_CONFIG_PATH > cwd walk — the same order config-path.ts (orch-monitor),
  // catalyst-execution-core and catalyst-monitor.sh already document and use, so a
  // caller that pins one var gets identical behavior across every daemon.
  for (const envVar of ["CATALYST_CONFIG_FILE", "CATALYST_CONFIG_PATH"]) {
    const pinned = process.env[envVar];
    if (pinned && existsSync(pinned)) return pinned;
  }
  // CATALYST_DIR-relative candidate: correct under launchd, where cwd is meaningless
  // but CATALYST_DIR is always set (or defaulted to ~/catalyst above).
  const dirCandidate = join(CATALYST_DIR, ".catalyst/config.json");
  if (existsSync(dirCandidate)) return dirCandidate;
  // Walk up from cwd — forward-start may be invoked from a repo subdirectory, so an
  // exact-cwd lookup would miss the repo-root .catalyst/config.json (Codex P2).
  let dir = process.cwd();
  for (let i = 0; i < 40; i++) {
    const p = join(dir, ".catalyst/config.json");
    if (existsSync(p)) return p;
    const parent = dirname(dir);
    if (parent === dir) break; // reached filesystem root
    dir = parent;
  }
  return null;
}
// CTL-1506 (Codex #2742 P1): record WHY the key resolved as it did, so the default is
// never silently indistinguishable from a real answer. Loading the wrong Layer-2 config
// degrades quietly (wrong endpoint/token) — exactly the class of failure that should be
// loud. Logged once at startup, after the logger exists.
let projectKeySource = "default";
function resolveProjectKey(): string {
  if (process.env.CATALYST_PROJECT_KEY) {
    projectKeySource = "env:CATALYST_PROJECT_KEY";
    return process.env.CATALYST_PROJECT_KEY;
  }
  const l1Path = findLayer1Config();
  if (l1Path) {
    try {
      const l1 = JSON.parse(readFileSync(l1Path, "utf8"));
      const key = l1?.catalyst?.projectKey;
      if (typeof key === "string" && key) {
        projectKeySource = `layer1:${l1Path}`;
        return key;
      }
      projectKeySource = `layer1-no-key:${l1Path}`;
    } catch {
      projectKeySource = `layer1-malformed:${l1Path}`;
    }
  } else {
    projectKeySource = "no-layer1-found";
  }
  return "catalyst-workspace";
}
const PROJECT_KEY = resolveProjectKey();
// Derive the Layer-2 path from the resolved project key (config-{projectKey}.json),
// still overridable wholesale via CATALYST_CONFIG_PATH.
const CONFIG_PATH =
  process.env.CATALYST_CONFIG_PATH ??
  join(homedir(), `.config/catalyst/config-${PROJECT_KEY}.json`);

const cfg = loadForwarderConfig(CONFIG_PATH, PROJECT_KEY);
const ck = readCheckpoint(CHECKPOINT_PATH);

// CTL-1818: apply the configured drop-surface thresholds (env still wins — see
// lib/drop-surface.ts's ladder). Done at module scope, not inside the `import.meta.main`
// block, so a sender constructed by any importer measures against the same thresholds.
configureDropSurface(cfg.otlp.dropSurface);

// CTL-1817: `unrecognized` counts lines the TAILER filtered out for matching no known
// envelope shape; `skippedNoAttributes` counts records that got past the tailer but were
// dropped by processLine for having no attributes. Both were previously folded into the
// undifferentiated `skipped`, which no surface reads — so a whole event family could vanish
// with every health signal green. They are reported on the pino log (Alloy-shipped,
// independent of this daemon's own OTLP egress), never as an event on the pipe they describe.
// CTL-1809: `torn` counts lines that did not parse as JSON AT ALL — the product of a bash
// producer's multi-write(2) append being interleaved by a concurrent producer. It is a
// strictly different failure from `unrecognized` (parses fine, matches no known envelope
// shape) and must not be folded into it: one says a producer emitted a shape we cannot map,
// the other says the log was damaged in transit. It is deliberately NOT added to `skipped`
// either — `skipped` counts records that reached processLine, and a torn line never does.
let stats = { processed: 0, skipped: 0, unrecognized: 0, skippedNoAttributes: 0, torn: 0 };

// CTL-1060 Phase 3: lag tracking state. lastLocalTs = newest event ts seen from the log.
// lastForwardedTs = newest event ts confirmed delivered to OTLP/Loki (seeded from checkpoint).
let lastLocalTs: string | undefined;
let lastForwardedTs: string | undefined = ck?.lastForwardedTs;

// 30-second cadence for forward_lag canonical events (CTL-1060 Phase 3).
// Tied to the OTLP/Loki path — this is the path the 2026-06-11 audit reported as "0 in Loki".
const LAG_EMIT_MS = 30_000;

/** Returns max of two ISO-8601 timestamps (or b when a is undefined). */
export function maxTs(a: string | undefined, b: string | undefined): string | undefined {
  if (!a) return b;
  if (!b) return a;
  return a >= b ? a : b;
}

/** Returns lagMs = localNewestTs - lastForwardedTs in ms, clamped to ≥ 0. Returns 0 when either timestamp is undefined. */
export function computeLagMs(
  localNewestTs: string | undefined,
  lastForwardedTs: string | undefined
): number {
  if (!localNewestTs || !lastForwardedTs) return 0;
  const delta = Date.parse(localNewestTs) - Date.parse(lastForwardedTs);
  return delta > 0 ? delta : 0;
}

/** Builds a canonical catalyst.observability.forward_lag event for the broker/HUD pipeline. */
export function buildLagEvent(opts: {
  localNewestTs: string | undefined;
  lastForwardedTs: string | undefined;
  dlqDepth: number;
}): CanonicalEvent {
  return buildCanonicalEnvelope({
    serviceName: "catalyst.otel-forward",
    eventName: "catalyst.observability.forward_lag",
    payload: {
      lagMs: computeLagMs(opts.localNewestTs, opts.lastForwardedTs),
      localNewestTs: opts.localNewestTs,
      lastForwardedTs: opts.lastForwardedTs,
      dlqDepth: opts.dlqDepth,
    },
  });
}

const buffers: { otlp: CanonicalEvent[]; posthog: CanonicalEvent[]; cae: CanonicalEvent[] } = {
  otlp: [],
  posthog: [],
  cae: [],
};

// CTL-1506 (Codex P2): resolve the log file on each use, not once at startup — a
// daemon that crosses a rotation boundary must write to the file the tailer now
// reads. CTL-1216 keeps that resolve-per-use property and moves the FILENAME
// onto lib/event-log-paths.mjs, the same resolver lib/tail.ts and
// execution-core/daemon-watchdog-predicates.mjs now use — which is what makes
// "the file the tailer now reads" a fact rather than three copies agreeing.
const currentEventLogPath = () =>
  join(EVENTS_DIR, eventLogBasenameFor(new Date(), resolveRotationScheme({ env: process.env })));

const OTLP_DLQ_PATH = join(CATALYST_DIR, "otel-forward-dlq-otlp.jsonl");

// CTL-1506 (Codex P1): module-scoped so senders can carry the shutdown signal — an
// aborted flush stops retrying and DLQs immediately, keeping shutdown inside the
// launcher's SIGKILL grace. The SIGTERM/SIGINT handlers below (in the main block) abort it.
const ac = new AbortController();

const senders = {
  otlp: cfg.otlp.enabled
    ? new OtlpSender({
        endpoint: cfg.otlp.endpoint,
        dlqPath: OTLP_DLQ_PATH,
        eventLogPath: currentEventLogPath,
        signal: ac.signal,
        // CTL-1506: age window + retry window from config
        lokiAcceptWindowMs: cfg.otlp.lokiAcceptWindowMs,
        httpRetryPolicy: { maxElapsedMs: cfg.otlp.maxRetryElapsedMs },
        // CTL-1060 Phase 3: advance lastForwardedTs on each confirmed-delivered batch.
        // CTL-1506 (Codex P2): only fold PARSEABLE timestamps into the watermark — an
        // unparseable ts (e.g. "not-a-date") is lexicographically larger than an ISO
        // string, so maxTs would pin lastForwardedTs to it, computeLagMs would then read
        // NaN (treated as 0), and forward-lag reporting would be silently suppressed —
        // persisted across restart via the checkpoint.
        onBatchDelivered: (batch) => {
          const batchMaxTs = batch.reduce((acc, ev) => {
            const t = (ev as CanonicalEvent).ts;
            return t && !Number.isNaN(Date.parse(t)) ? maxTs(acc, t) : acc;
          }, undefined as string | undefined);
          lastForwardedTs = maxTs(lastForwardedTs, batchMaxTs);
        },
      })
    : null,
  posthog: cfg.posthog.enabled
    ? new PosthogSender({
        apiKey: cfg.posthog.apiKey,
        host: cfg.posthog.host,
        dlqPath: join(CATALYST_DIR, "otel-forward-dlq-posthog.jsonl"),
      })
    : null,
  cae: cfg.cloudflareAE.enabled
    ? new CloudflareAESender({
        accountId: cfg.cloudflareAE.accountId,
        apiToken: cfg.cloudflareAE.apiToken,
        dataset: cfg.cloudflareAE.dataset,
        dlqPath: join(CATALYST_DIR, "otel-forward-dlq-cae.jsonl"),
      })
    : null,
};

/**
 * The 30 s tick body. EXPORTED for the CTL-1818 wiring test, not for production use — the
 * `lagTimer` in the `import.meta.main` block below is its only runtime caller.
 *
 * Why it has to be exported: the drop surface's alert-CLEAR branch (`lib/drop-surface.ts`) is
 * reachable from `evaluateDropSurface()` and from nothing else, so a test that calls that
 * function directly passes whether or not this daemon ever calls it — which is exactly how the
 * call below survived deletion with a fully green suite. Exporting the tick lets the test assert
 * the CALL (raise a latched alert, run one tick, watch it clear) rather than the callee in
 * isolation. See index-drop-wiring.test.ts.
 */
export function emitLag(): void {
  // CTL-1280: deterministic liveness heartbeat to otel-forward.log (Alloy→Loki),
  // emitted UNCONDITIONALLY each tick — BEFORE the cold-start skip below — so an
  // idle/quiet forwarder still proves it is alive (it previously wrote only a
  // startup line then went silent, reading as down). Rides the Alloy .log stream,
  // independent of the event pipeline this daemon itself ships.
  logDaemonHeartbeat(log, "otel-forward");
  // CTL-1517: per-process RSS/heap OTel gauge on the same tick (fire-and-forget; never
  // throws, never blocks) so per-daemon memory becomes attributable in Prometheus.
  void emitProcessMemoryMetric({ serviceName: "catalyst.otel-forward", log });
  // CTL-1818: re-evaluate the host-local drop surface on the same 30 s tick. Two things no
  // drop-driven call can do: CLEAR a latched sustained-loss alert on a host that recovered
  // and went quiet (nothing else re-evaluates once the drops stop), and keep the marker's
  // rolling-window figures honest while nothing is being discarded. Best-effort, never throws.
  // Placed BEFORE the cold-start skip below for the same reason CTL-1280's heartbeat is: the
  // skip is about the lag EVENT having nothing to report, and a forwarder with a latched drop
  // alert must still be able to clear it. index-drop-wiring.test.ts asserts this call.
  evaluateDropSurface();
  // Skip on cold start before any event has been processed or delivered
  if (!lastLocalTs && !lastForwardedTs) return;
  try {
    const ev = buildLagEvent({
      localNewestTs: lastLocalTs,
      lastForwardedTs,
      dlqDepth: dlqDepth(OTLP_DLQ_PATH),
    });
    const logPath = currentEventLogPath(); // CTL-1506: resolve per emission (month rollover)
    mkdirSync(dirname(logPath), { recursive: true });
    appendFileSync(logPath, JSON.stringify(ev) + "\n");
  } catch {
    // Best-effort — must never throw
  }
}

// CTL-1817: best-effort identity for a line that is, by definition, not in a shape we can
// read, so a dropped record can be NAMED rather than reported as an anonymous tally, with a
// bounded raw prefix as the fallback. Never throws — it runs on the drop path.
//
// CTL-1834: this was the repo's ONLY correct three-key reader, hand-rolled on the drop path
// while the shared boundary read two. It now delegates. Precedence is unobservable here BY
// CONSTRUCTION: both callers sit behind `shouldForward` having already REJECTED the line, so
// the line has no `attributes` key and no string `event` — only the v3 arm can ever fire.
export function describeUnknownShape(line: string): string {
  try {
    const o = JSON.parse(line) as Record<string, unknown>;
    const name = getEventName(o);
    if (name) return name;
    return `(no name; keys: ${Object.keys(o).slice(0, 6).join(",")})`;
  } catch {
    return `(unparseable: ${line.slice(0, 60)})`;
  }
}

// CTL-1817: COUNT EVERY OCCURRENCE, LOG SPARSELY. The gate itself moved to
// lib/sparse-warn.ts in CTL-1818 (unchanged semantics: first sighting per distinct key, then
// 10/100/1000… heartbeats, capped key set) so the drop surface reuses the SAME mechanism
// rather than growing a second one beside it. This gate keeps its own key budget — a flood of
// unknown envelope shapes must not exhaust the one the drop alarm depends on.
const shouldWarnForShape = createSparseWarnGate({ maxTracked: 50 });

// Wired into the tailer as onUnrecognized. This is the ONLY place that can see a line the
// tailer's shouldForward filter discards, because such a line never reaches processLine.
export function noteUnrecognizedLine(line: string): void {
  stats.unrecognized++;
  const event = describeUnknownShape(line);
  if (!shouldWarnForShape(`u:${event}`, stats.unrecognized)) return;
  log.warn(
    { event, unrecognized_total: stats.unrecognized },
    "unrecognized envelope shape — line dropped by the tailer, never forwarded (CTL-1817)",
  );
}

// CTL-1809: its own gate, not shouldWarnForShape's. A torn line's "key" is a raw byte
// prefix, so a sustained tear produces a near-unique key per line — sharing the shape gate
// would exhaust the 50-key budget that the unknown-envelope alarm depends on within 50
// lines, silencing a completely different detector. Same reason CTL-1818 gave each caller
// its own gate in the first place.
const shouldWarnForTear = createSparseWarnGate({ maxTracked: 20 });

// Wired into the tailer as onUnparseable. The tailer's JSON.parse catch is the ONLY place in
// this process that can see a torn line — it never reaches shouldForward's shape test, let
// alone processLine.
//
// The counter is a LOWER BOUND on corruption, never proof of cleanliness. The CTL-1809 RCA
// reproduced a splice that parses as valid JSON, whose declared length matches, and whose
// contents are three different events; nothing here or in any other parser can see that.
// The write side (lib/canonical-event.sh's one-write(2) primitive) is the fix — this is the
// tripwire that says the fix is not holding somewhere.
//
// Note for whoever reads these numbers across hosts: a MONITOR node's count will legitimately
// exceed a worker's. event-mirror is a transport, not a repair layer — a torn line has no
// extractable event id, so its dedup ring cannot suppress it and it is always appended
// (event-mirror/lib/state.ts), faithfully propagating worker-host damage plus any duplicates
// from a cursor-0 re-read.
export function noteUnparseableLine(line: string): void {
  stats.torn++;
  // A torn line has no name to report, by definition — a bounded raw prefix is the only
  // identity available, and it is what an operator greps the source log for.
  const prefix = line.slice(0, 60);
  if (!shouldWarnForTear(`t:${prefix}`, stats.torn)) return;
  log.warn(
    { prefix, torn_total: stats.torn, bytes: line.length },
    "TORN event-log line — did not parse as JSON; counted and skipped, never forwarded (CTL-1809)",
  );
}

export function processLine(line: string): void {
  try {
    let ev = JSON.parse(line) as CanonicalEvent;
    // pino BEFORE flat: an execution-core pino WARN/ERROR may carry a structured
    // `event` field (e.g. reaper.mjs), which isFlatEvent would otherwise claim
    // and strip of its severity. isPinoRecord (numeric level + string msg) never
    // matches a real flat catalyst event, so this ordering is safe (CTL-1424).
    if (isPinoRecord(ev)) ev = normalizePinoRecord(ev as unknown as Record<string, unknown>);
    else if (isFlatEvent(ev)) ev = normalizeFlatEvent(ev as unknown as Record<string, unknown>);
    if (!ev.attributes) {
      // CTL-1817: a record that survived the tailer but carries no attributes is dropped
      // here. Name it so the loss is diagnosable — reading all three shapes, because a
      // record that reaches this branch is by definition not in the shape we expect.
      stats.skipped++;
      stats.skippedNoAttributes++;
      const event = describeUnknownShape(line);
      // Same count-always / log-sparsely discipline as noteUnrecognizedLine above.
      if (shouldWarnForShape(`n:${event}`, stats.skippedNoAttributes)) {
        log.warn(
          { event, skipped_no_attributes: stats.skippedNoAttributes },
          "dropping record with no attributes — it will not be forwarded (CTL-1817)",
        );
      }
      return;
    }
    stats.processed++;
    // Track newest local event timestamp for lag metric (CTL-1060 Phase 3).
    // CTL-1506 (Codex P2): guard parseability so a malformed ts can't poison the watermark.
    if (ev.ts && !Number.isNaN(Date.parse(ev.ts))) lastLocalTs = maxTs(lastLocalTs, ev.ts);
    if (senders.otlp) buffers.otlp.push(ev);
    if (senders.posthog) buffers.posthog.push(ev);
    if (senders.cae) buffers.cae.push(ev);
  } catch {
    stats.skipped++;
  }
}

export function getStats() {
  return { ...stats };
}

// CTL-1506 (Codex #2742 P1): the checkpoint-advance decision, extracted pure so the
// "never persist past in-memory events" invariant is unit-testable rather than buried in
// the timer. Returns the position to persist: the live read position ONLY when every
// destination is drained (buffered events flushed AND no flush in flight — a resolved
// flush means durable, delivered or DLQ'd); otherwise the previous durable position,
// unchanged. Monotonic within a file: never returns an offset lower than `prev` for the
// same path, so a transient drain can't rewind the checkpoint.
export function nextDurableCheckpoint(args: {
  drained: boolean;
  currentPath: string;
  currentOffset: number;
  prevPath: string;
  prevOffset: number;
}): { path: string; offset: number } {
  const { drained, currentPath, currentOffset, prevPath, prevOffset } = args;
  if (!drained) return { path: prevPath, offset: prevOffset };
  // Rotated to a new file → adopt it outright (offsets are per-file, not comparable).
  if (currentPath !== prevPath) return { path: currentPath, offset: currentOffset };
  return { path: currentPath, offset: Math.max(prevOffset, currentOffset) };
}

type DestKey = "otlp" | "posthog" | "cae";

// CTL-1506 (Codex P1/P2): serialize each destination's flushes INDEPENDENTLY. A sender's
// flush() opens a retry window up to maxRetryElapsedMs (default 60 s) while the flush
// timer fires far more often. A PER-DESTINATION in-flight guard keeps OTLP's DLQ access
// race-free (no two OtlpSender.flush concurrently entering drainDlqBounded against the
// same file) WITHOUT coupling healthy sinks to a slow one — a tick for PostHog/CFAE
// still flushes while OTLP is mid-retry, so their events don't sit in memory (which,
// with the checkpoint advancing, a restart could otherwise skip).
const inFlight: Record<DestKey, Promise<void> | null> = { otlp: null, posthog: null, cae: null };

function flushDest(
  key: DestKey,
  sender: { flush: (b: CanonicalEvent[]) => Promise<void> } | null,
  buffer: CanonicalEvent[]
): Promise<void> {
  if (!sender || buffer.length === 0) return Promise.resolve();
  if (inFlight[key]) return inFlight[key]!; // coalesce this destination's tick
  // CTL-1506: drain the whole buffer in a single flush() so the sender's own DLQ drain
  // runs exactly once per cycle (CTL-1060 per-cycle cap) and no spliced-out remainder can
  // be lost. batchSize is advisory only — see the config reference. A sender.flush() never
  // rejects in normal operation (it DLQs its own failures); the timer .catch below is the
  // backstop for an exceptional storage error.
  const p = sender.flush(buffer.splice(0)).finally(() => {
    inFlight[key] = null;
  });
  inFlight[key] = p;
  return p;
}

async function flushAll(): Promise<void> {
  await Promise.allSettled([
    flushDest("otlp", senders.otlp, buffers.otlp),
    flushDest("posthog", senders.posthog, buffers.posthog),
    flushDest("cae", senders.cae, buffers.cae),
  ]);
}

if (import.meta.main) {
  process.on("SIGTERM", () => {
    ac.abort();
  });
  process.on("SIGINT", () => {
    ac.abort();
  });

  const tailer = createTailer({
    eventsDir: EVENTS_DIR,
    offset: ck?.offset ?? 0,
    onLine: processLine,
    onUnrecognized: noteUnrecognizedLine, // CTL-1817: make the tailer's silent drop loud
    onUnparseable: noteUnparseableLine, // CTL-1809: make the tailer's silent TORN line loud
    signal: ac.signal,
  });

  // CTL-1506 (Codex P2): one timer PER enabled destination at its OWN flushIntervalMs,
  // so a per-forwarder cadence actually takes effect (the old single global-min timer
  // flushed every sink at the fastest configured interval).
  // CTL-1506 (Codex P1): each timer swallows its flush rejection (logs it) — Bun treats an
  // unhandled promise rejection as fatal, so a storage/DLQ error in one destination must
  // not take down the whole daemon (the old global timer consumed rejections via allSettled).
  const onFlushError = (dest: string) => (err: unknown) =>
    log.error({ dest, err: err instanceof Error ? err.message : String(err) }, "scheduled flush failed");
  const flushTimers: ReturnType<typeof setInterval>[] = [];
  if (senders.otlp) {
    flushTimers.push(setInterval(() => {
      flushDest("otlp", senders.otlp, buffers.otlp).catch(onFlushError("otlp"));
    }, cfg.otlp.flushIntervalMs));
  }
  if (senders.posthog) {
    flushTimers.push(setInterval(() => {
      flushDest("posthog", senders.posthog, buffers.posthog).catch(onFlushError("posthog"));
    }, cfg.posthog.flushIntervalMs));
  }
  if (senders.cae) {
    flushTimers.push(setInterval(() => {
      flushDest("cae", senders.cae, buffers.cae).catch(onFlushError("cae"));
    }, cfg.cloudflareAE.flushIntervalMs));
  }

  // CTL-1506 (Codex #2742 P1): the checkpoint must never advance PAST events that are
  // still only in memory. tailer.currentOffset() is the READ position; an event is not
  // durable until its destination's flush() resolves (delivered, or DLQ'd — the sender
  // DLQs its own failures, so a resolved flush means durable either way). While OTLP is
  // inside its retry window (default 60 s) flushDest coalesces every tick onto the
  // existing promise and the buffer keeps growing — yet this timer was persisting an
  // ever-advancing offset. A hard crash in that window resumed from beyond those events,
  // dropping them permanently.
  //
  // Fix: only advance the persisted offset at moments when EVERY destination is fully
  // drained (no buffered events, no flush in flight). Between such moments the previous
  // floor is re-persisted, so a crash replays from the last provably-durable position.
  // Deliberately conservative: a stalled sink holds the floor back, which costs replayed
  // (duplicate) events on restart rather than lost ones — the correct direction for an
  // observability forwarder, and the direction the DLQ already assumes.
  let durableOffset = ck?.offset ?? 0;
  let durablePath = ck?.path ?? tailer.currentPath();
  const allDrained = () =>
    buffers.otlp.length === 0 &&
    buffers.posthog.length === 0 &&
    buffers.cae.length === 0 &&
    !inFlight.otlp &&
    !inFlight.posthog &&
    !inFlight.cae;

  const ckTimer = setInterval(() => {
    const next = nextDurableCheckpoint({
      drained: allDrained(),
      currentPath: tailer.currentPath(),
      currentOffset: tailer.currentOffset(),
      prevPath: durablePath,
      prevOffset: durableOffset,
    });
    durablePath = next.path;
    durableOffset = next.offset;
    writeCheckpoint(CHECKPOINT_PATH, { path: durablePath, offset: durableOffset, lastForwardedTs });
  }, 10_000);

  // CTL-1060 Phase 3: emit forward_lag canonical event every 30 s.
  const lagTimer = setInterval(emitLag, LAG_EMIT_MS);

  // CTL-1506 (Codex #2742 P1): surface the project-key provenance. When it fell back to
  // the default WITHOUT a Layer-1 file, warn — under launchd that is the signature of a
  // non-default project silently loading the wrong Layer-2 config.
  if (projectKeySource === "default" || projectKeySource.startsWith("no-layer1")) {
    log.warn(
      { projectKey: PROJECT_KEY, source: projectKeySource, cwd: process.cwd(), catalystDir: CATALYST_DIR },
      "project key fell back to the default — no Layer-1 config found; pin CATALYST_CONFIG_FILE if this is not the intended project"
    );
  } else {
    log.info({ projectKey: PROJECT_KEY, source: projectKeySource }, "project key resolved");
  }

  log.info(
    {
      otlpEnabled: cfg.otlp.enabled,
      posthogEnabled: cfg.posthog.enabled,
      cfaeEnabled: cfg.cloudflareAE.enabled,
    },
    "started"
  );

  await tailer.run();

  for (const t of flushTimers) clearInterval(t);
  clearInterval(ckTimer);
  clearInterval(lagTimer);
  // CTL-1506 (Codex P1): shutdown is BOUNDED. ac.abort() (from the SIGTERM/SIGINT handlers)
  // makes any in-flight retry stop and DLQ, and flushAll drains each buffer in one pass
  // (each retry now aborts fast → DLQ), so this completes well inside the launcher's grace
  // instead of waiting out a full 60s retry window.
  await Promise.allSettled(Object.values(inFlight).filter((p): p is Promise<void> => p !== null));
  // CTL-1506 (Codex #2742 P1): after the bounded drain above, everything read is durable,
  // so persist the true read position. Without this the conservative floor would make a
  // CLEAN shutdown replay its last buffered batch on every restart.
  if (allDrained()) {
    writeCheckpoint(CHECKPOINT_PATH, {
      path: tailer.currentPath(),
      offset: tailer.currentOffset(),
      lastForwardedTs,
    });
  }
  await flushAll();
  // CTL-1809: `torn` on the shutdown line too — the sparse gate above means a long, slow
  // tear may only ever have logged its first sighting, so this is the one place the
  // process-total is guaranteed to be reported.
  log.info({ processed: stats.processed, skipped: stats.skipped, torn: stats.torn }, "stopped");
}
