#!/usr/bin/env bash
# Usage: generate-index.sh <dir-label>
#
# Reads scored JSONL on stdin (output of score.sh). Writes INDEX.md to stdout
# with three sections (Current / Needs Review / Likely Stale). Entries within
# each section are sorted by date descending. Output is fully deterministic —
# same input bytes produce same output bytes (no timestamps in the body).

set -uo pipefail

LABEL="${1:-corpus}"

# Slurp stdin into a single JSON array for sorting / grouping in jq.
ENTRIES=$(jq -s '.' </dev/stdin)

# Helper: emit one section, sorted by date descending. Returns empty string
# when no entries match the filter.
emit_section() {
  local heading="$1" status="$2"
  local section
  section=$(jq -r --arg s "$status" '
    map(select(.status == $s))
    | sort_by(.date) | reverse
    | .[]
    | (.filename | sub("\\.md$"; "")) as $slug
    | (.topic // $slug) as $summary
    | "- [[\($slug)]] — \($summary) (\(.date))" +
      (if .status == "needs-review" then
         (if .broken_refs > 0 then " — _\(.broken_refs) broken ref(s)_" else " — _age \(.age_days)d_" end)
       elif .status == "likely-stale" then
         " — _no recent activity (\(.age_days)d old)_"
       else "" end)
  ' <<<"$ENTRIES")

  if [[ -n "$section" ]]; then
    printf '## %s\n\n%s\n\n' "$heading" "$section"
  else
    printf '## %s\n\n_(none)_\n\n' "$heading"
  fi
}

# Header — deliberately omits any "generated on <date>" line to keep the
# output deterministic across runs. The skill's run.sh writes a header
# comment file alongside if a timestamp is desired.

printf '# INDEX — %s\n\n' "$LABEL"
printf '_Generated by `/catalyst-foundry:research-curate`. Source docs untouched._\n\n'

emit_section "Current" "current"
emit_section "Needs Review" "needs-review"
emit_section "Likely Stale" "likely-stale"
