#!/usr/bin/env bash
# install-cli.sh — install symlinks for every catalyst-* CLI.
#
# Usage:
#   install-cli.sh                    # install/update symlinks (idempotent)
#   install-cli.sh --bin-dir <path>   # install into <path> instead of the default
#   install-cli.sh --force            # accepted for backward compat (currently a no-op)
#   install-cli.sh --uninstall        # remove catalyst-* symlinks, rmdir if empty
#   install-cli.sh --help
#
# Default bin dir resolution (highest precedence first):
#   1. --bin-dir <path>
#   2. CATALYST_BIN_DIR env var
#   3. CATALYST_CLI_BIN_DIR env var (backward compat)
#   4. $HOME/.catalyst/bin (the canonical Catalyst home — matches ~/.cargo/bin,
#      ~/.volta/bin, ~/.deno/bin, ~/.bun/bin)
#
# Behavior on install:
#   - Sweep stale source-repo symlinks at $BIN_DIR/catalyst-* (Apr 2026-era
#     pre-cache installs that bypass plugin version pinning).
#   - Sweep our own shims from ~/.local/bin/catalyst-* (legacy default before
#     CTL-339) so PATH-order accidents don't cause shadowing.
#   - Bootstrap PATH: if $BIN_DIR is not on PATH, append an export line to the
#     user's shell rc file (idempotent — marker comment prevents duplicates).
#
# Env overrides (primarily for tests):
#   CATALYST_CLI_SOURCE    default: auto-detected (CLAUDE_PLUGIN_ROOT/scripts or this script's dir)
#   CATALYST_BIN_DIR       default: $HOME/.catalyst/bin
#   CATALYST_CLI_BIN_DIR   backward-compat alias for CATALYST_BIN_DIR

set -uo pipefail

# Explicit allowlist. Source name → installed command name (.sh suffix stripped).
# Keep this in sync with check-setup.sh's "Catalyst CLI Install" section.
CLI_ENTRIES=(
  "catalyst-broker:catalyst-broker"
  "catalyst-comms:catalyst-comms"
  "catalyst-events:catalyst-events"
  "catalyst-filter:catalyst-filter"
  "catalyst-session.sh:catalyst-session"
  "catalyst-state.sh:catalyst-state"
  "catalyst-db.sh:catalyst-db"
  "catalyst-monitor.sh:catalyst-monitor"
  "catalyst-thoughts.sh:catalyst-thoughts"
  "catalyst-claude.sh:catalyst-claude"
  "register-thought.sh:register-thought"
  "workflow-context.sh:workflow-context"
  "catalyst-hud:catalyst-hud"
  "catalyst-hud-classic.sh:catalyst-hud-classic"
  "../hooks/emit-lifecycle-event.sh:emit-lifecycle-event"
)

# Marker embedded in generated wrapper shims so the ~/.local/bin sweep can
# identify shims we previously wrote there without touching unrelated files.
WRAPPER_MARKER="Auto-generated by catalyst install-cli.sh"

usage() {
  cat <<'EOF'
Usage: install-cli.sh [--bin-dir <path>] [--force] [--uninstall] [--help]

Installs symlinks for every catalyst-* CLI so they can be invoked by name
from any shell.

Default bin dir: $HOME/.catalyst/bin (matches ~/.cargo/bin, ~/.volta/bin,
~/.deno/bin, ~/.bun/bin — `rm -rf ~/.catalyst/` removes every trace).

Options:
  --bin-dir <path>   Install symlinks into <path> instead of the default
  --force            Accepted for backward compat (currently a no-op; PATH
                     bootstrap is always attempted)
  --uninstall        Remove previously-installed catalyst-* symlinks
  --help, -h         Show this help

Environment overrides (for testing):
  CATALYST_CLI_SOURCE    Source directory containing catalyst-* scripts
  CATALYST_BIN_DIR       Target directory for symlinks (overrides default)
  CATALYST_CLI_BIN_DIR   Backward-compat alias for CATALYST_BIN_DIR
EOF
}

resolve_source() {
  if [[ -n "${CATALYST_CLI_SOURCE:-}" ]]; then
    echo "$CATALYST_CLI_SOURCE"
    return
  fi
  if [[ -n "${CLAUDE_PLUGIN_ROOT:-}" && -d "${CLAUDE_PLUGIN_ROOT}/scripts" ]]; then
    echo "${CLAUDE_PLUGIN_ROOT}/scripts"
    return
  fi
  # Fall back to the directory of this running script
  local self_dir
  self_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  echo "$self_dir"
}

# Resolve bin dir in precedence order: --bin-dir override > CATALYST_BIN_DIR >
# CATALYST_CLI_BIN_DIR (backward compat) > $HOME/.catalyst/bin (always).
# Pre-CTL-339, this preferred $HOME/.local/bin when the directory existed;
# that caused PATH-order accidents where legacy ~/.catalyst/bin symlinks
# shadowed the cache-aware shims at ~/.local/bin and silently bypassed plugin
# version pinning. The canonical Catalyst home is ~/.catalyst/bin/ — same
# pattern as Cargo, Volta, Deno, Bun.
resolve_bin_dir() {
  if [[ -n "${BIN_DIR_OVERRIDE:-}" ]]; then
    echo "$BIN_DIR_OVERRIDE"
    return
  fi
  if [[ -n "${CATALYST_BIN_DIR:-}" ]]; then
    echo "$CATALYST_BIN_DIR"
    return
  fi
  if [[ -n "${CATALYST_CLI_BIN_DIR:-}" ]]; then
    echo "$CATALYST_CLI_BIN_DIR"
    return
  fi
  echo "$HOME/.catalyst/bin"
}

mode="install"
BIN_DIR_OVERRIDE=""
FORCE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --uninstall) mode="uninstall"; shift ;;
    --bin-dir)
      if [[ $# -lt 2 || -z "$2" ]]; then
        echo "error: --bin-dir requires a path argument" >&2
        usage >&2
        exit 2
      fi
      BIN_DIR_OVERRIDE="$2"
      shift 2
      ;;
    --force) FORCE=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "error: unknown flag: $1" >&2; usage >&2; exit 2 ;;
  esac
done

BIN_DIR="$(resolve_bin_dir)"

if [[ "$mode" = "uninstall" ]]; then
  if [[ -d "$BIN_DIR" ]]; then
    for entry in "${CLI_ENTRIES[@]}"; do
      dest_name="${entry##*:}"
      link="$BIN_DIR/$dest_name"
      if [[ -L "$link" || -e "$link" ]]; then
        rm -f "$link"
      fi
    done
    # rmdir quietly — fails if dir has other entries, which is fine
    rmdir "$BIN_DIR" 2>/dev/null || true
    echo "Removed catalyst CLI symlinks from $BIN_DIR"
  else
    echo "$BIN_DIR does not exist — nothing to uninstall"
  fi
  exit 0
fi

# install mode
SOURCE_DIR="$(resolve_source)"
if [[ ! -d "$SOURCE_DIR" ]]; then
  echo "error: source directory not found: $SOURCE_DIR" >&2
  echo "hint: set CATALYST_CLI_SOURCE or CLAUDE_PLUGIN_ROOT" >&2
  exit 1
fi

mkdir -p "$BIN_DIR"

# Sweep stale source-repo symlinks at $BIN_DIR/catalyst-* before writing new
# shims. These are pre-cache (Apr 2026) installs that point directly into a
# source-repo clone (e.g. ~/code-repos/.../plugins/dev/scripts/). On a machine
# with both ~/.catalyst/bin and ~/.local/bin on PATH, these legacy symlinks
# shadowed cache-aware shims and silently bypassed plugin version pinning.
#
# Filter:
#   - glob limited to catalyst-* (preserves register-thought, workflow-context
#     source symlinks — those are still valid)
#   - only symlinks
#   - readlink target contains /plugins/dev/scripts/ but is NOT under the
#     plugin cache (~/.claude/plugins/cache/) — i.e. direct clone, not cache
sweep_stale_target_symlinks() {
  local removed=0
  local link target
  # Use a nullglob-safe pattern via [[ -e ]] guard. find is more robust here
  # than a shell glob since we need readlink behavior on every match.
  while IFS= read -r link; do
    [[ -L "$link" ]] || continue
    target=$(readlink "$link" 2>/dev/null || true)
    [[ -n "$target" ]] || continue
    case "$target" in
      *"/plugins/dev/scripts/"*)
        case "$target" in
          "${HOME}/.claude/plugins/cache/"*) ;;  # legitimate cache link — keep
          *)
            rm -f "$link"
            removed=$((removed + 1))
            ;;
        esac
        ;;
    esac
  done < <(find "$BIN_DIR" -maxdepth 1 -name 'catalyst-*' -type l 2>/dev/null)
  if [[ "$removed" -gt 0 ]]; then
    echo "  Swept $removed stale source-repo symlink(s) from $BIN_DIR"
  fi
}

# Sweep our own shims from ~/.local/bin/catalyst-* — legacy default before
# CTL-339 (when ~/.local/bin existed, install-cli.sh wrote shims there). Leave
# files we don't recognize alone. Skip entirely if $BIN_DIR IS ~/.local/bin
# (don't sweep what we're about to install into).
sweep_local_bin() {
  local local_bin="${HOME}/.local/bin"
  [[ -d "$local_bin" ]] || return 0
  [[ "$BIN_DIR" != "$local_bin" ]] || return 0
  local removed=0
  local entry dest_name candidate target first_line
  for entry in "${CLI_ENTRIES[@]}"; do
    dest_name="${entry##*:}"
    candidate="$local_bin/$dest_name"
    if [[ -L "$candidate" ]]; then
      target=$(readlink "$candidate" 2>/dev/null || true)
      case "$target" in
        *"/plugins/dev/scripts/"*)
          rm -f "$candidate"
          removed=$((removed + 1))
          ;;
      esac
    elif [[ -f "$candidate" ]]; then
      # Inspect first ~4 lines for the wrapper marker so we never delete
      # unrelated user scripts that happen to share a catalyst-* name.
      first_line=$(head -n 4 "$candidate" 2>/dev/null || true)
      if [[ "$first_line" == *"$WRAPPER_MARKER"* ]]; then
        rm -f "$candidate"
        removed=$((removed + 1))
      fi
    fi
  done
  if [[ "$removed" -gt 0 ]]; then
    echo "  Swept $removed legacy shim(s) from $local_bin"
  fi
}

sweep_stale_target_symlinks
sweep_local_bin

# When source is inside the plugin cache, write version-discovering wrappers so
# plugin upgrades take effect immediately without re-running install-cli.sh.
# When source is a local clone (dev/test workflow), use direct symlinks instead.
use_wrapper=0
if [[ "$SOURCE_DIR" == "${HOME}/.claude/plugins/cache/"* ]]; then
  use_wrapper=1
fi

installed=0
missing=0
for entry in "${CLI_ENTRIES[@]}"; do
  src_name="${entry%%:*}"
  dest_name="${entry##*:}"
  src="$SOURCE_DIR/$src_name"
  link="$BIN_DIR/$dest_name"

  if [[ ! -f "$src" ]]; then
    echo "  skip: $src_name (not in source)" >&2
    missing=$((missing + 1))
    continue
  fi

  # Replace any existing link/file so re-point works
  rm -f "$link"
  if [[ "$use_wrapper" -eq 1 ]]; then
    # Write a tiny wrapper that auto-discovers the latest installed plugin
    # version at invocation time — survives plugin upgrades without re-install.
    # The first comment line is the WRAPPER_MARKER detection signal for the
    # ~/.local/bin sweep above.
    # CTL-390: wrapper intercepts --version|-V, prints its own resolution path,
    # then exec's the resolved CLI with --version so the underlying tool's
    # three-line version block follows.
    {
      echo '#!/usr/bin/env bash'
      echo "# ${WRAPPER_MARKER} (version-auto) — do not edit"
      echo '_CACHE="${HOME}/.claude/plugins/cache/catalyst/catalyst-dev"'
      echo '_LATEST=$(ls -d "${_CACHE}"/[0-9]*.*.*/ 2>/dev/null | sort -V | tail -1 | sed '"'"'s|/$||'"'"')'
      echo '[[ -z "${_LATEST}" ]] && { echo "error: catalyst-dev plugin not found in ${_CACHE}" >&2; exit 1; }'
      echo 'case "${1:-}" in --version|-V)'
      echo "  echo \"${dest_name} wrapper (\${BASH_SOURCE[0]})\""
      echo "  echo \"resolves to: \${_LATEST}/scripts/${src_name}\""
      echo '  echo "forwarding to underlying CLI for full version info..."'
      echo '  echo ""'
      echo "  exec \"\${_LATEST}/scripts/${src_name}\" --version ;;"
      echo 'esac'
      echo "exec \"\${_LATEST}/scripts/${src_name}\" \"\$@\""
    } > "$link"
    chmod +x "$link"
  else
    ln -s "$src" "$link"
  fi
  installed=$((installed + 1))
done

echo "Installed $installed catalyst CLI symlink(s) in $BIN_DIR"
if [[ $missing -gt 0 ]]; then
  echo "  ($missing expected scripts were missing from $SOURCE_DIR)"
fi

# Stale-alias detection — warns (never fails) about user-defined aliases that
# point at a local catalyst clone. These shadow the marketplace install in
# interactive shells; users should remove them so there's a single source of
# truth.
detect_stale_aliases() {
  local rc_files=("$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.zprofile" "$HOME/.bash_profile")
  local pattern='^[[:space:]]*alias[[:space:]]+catalyst-[a-z]+=.*plugins/dev/scripts/'
  local found=0
  for rc in "${rc_files[@]}"; do
    [[ -f "$rc" ]] || continue
    if grep -qE "$pattern" "$rc" 2>/dev/null; then
      if [[ "$found" -eq 0 ]]; then
        echo "" >&2
        echo "  ⚠️  Stale catalyst-* aliases detected (shadow installed CLIs):" >&2
        found=1
      fi
      grep -nE "$pattern" "$rc" 2>/dev/null \
        | sed "s|^|      $(basename "$rc"):|" >&2
    fi
  done
  if [[ "$found" -eq 1 ]]; then
    cat <<'EOF' >&2

  Remove these aliases so the marketplace install becomes the single source of truth.

EOF
  fi
}

detect_stale_aliases

# PATH bootstrap — if BIN_DIR is not on PATH, append an export line to the
# user's shell rc file. Idempotent: a marker comment guards against duplicate
# appends on repeat runs. Detects shell via $SHELL basename (zsh/bash/fish);
# falls back to ~/.profile if SHELL is unset or unrecognized.
ensure_path_bootstrap() {
  local marker="# Added by catalyst install-cli.sh"
  local shell_name rc_file export_line

  case "${SHELL:-}" in
    */zsh)  shell_name=zsh;  rc_file="$HOME/.zshrc" ;;
    */bash) shell_name=bash; rc_file="$HOME/.bashrc" ;;
    */fish) shell_name=fish; rc_file="$HOME/.config/fish/config.fish" ;;
    *)      shell_name=sh;   rc_file="$HOME/.profile" ;;
  esac

  if [[ "$shell_name" = "fish" ]]; then
    export_line="set -gx PATH \"$BIN_DIR\" \$PATH"
  else
    export_line="export PATH=\"$BIN_DIR:\$PATH\""
  fi

  # Already on PATH — print the suggested line for audit but don't modify rc.
  case ":${PATH:-}:" in
    *":$BIN_DIR:"*)
      echo "  $BIN_DIR is on PATH."
      return 0
      ;;
  esac

  # Append to rc file if marker not already present (idempotent).
  if [[ -f "$rc_file" ]] && grep -qF "$marker" "$rc_file" 2>/dev/null; then
    echo "  PATH bootstrap already present in $rc_file"
    echo "      $export_line"
    return 0
  fi

  mkdir -p "$(dirname "$rc_file")"
  {
    echo ""
    echo "$marker"
    echo "$export_line"
  } >> "$rc_file"

  echo ""
  echo "  Added $BIN_DIR to PATH via $rc_file:"
  echo "      $export_line"
  echo "  Open a new terminal (or: source $rc_file) to pick up the change."
  echo ""
}

ensure_path_bootstrap
