// linear-react.mjs <ISSUE> [--emoji eyes] [--remove] — react (as the app actor) to the latest HUMAN comment on an issue
const GQL="https://api.linear.app/graphql", OAUTH="https://api.linear.app/oauth/token";
const key=process.argv[2]; const emoji=(process.argv.indexOf("--emoji")>=0?process.argv[process.argv.indexOf("--emoji")+1]:"eyes"); const remove=process.argv.includes("--remove");
const r=await fetch(OAUTH,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"client_credentials",client_id:process.env.LINEAR_SYNC_CLIENT_ID,client_secret:process.env.LINEAR_SYNC_CLIENT_SECRET,scope:"read,write,comments:create,app:assignable,app:mentionable",actor:"app"})}); const tok=(await r.json()).access_token;
const g=async(q,v)=>{const x=await fetch(GQL,{method:"POST",headers:{"content-type":"application/json",authorization:tok},body:JSON.stringify({query:q,variables:v})});const j=await x.json(); if(j.errors) throw new Error(JSON.stringify(j.errors).slice(0,300)); return j.data;};
const d=await g(`query($k:String!){ issue(id:$k){ comments(first:100, orderBy: createdAt){ nodes{ id createdAt user{ id name } botActor{ type } reactions{ id emoji user{ id } } } } } }`,{k:key});
const humans=d.issue.comments.nodes.filter(n=>n.user&&!n.botActor&&n.user.id===(process.env.ASK_HUMAN_ID||"c2a8cc92-cab6-4536-9500-0f24abdf702b")).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)); const last=humans[humans.length-1]; if(!last){console.log("no human comment");process.exit(0);}
if(remove){ const mine=last.reactions.filter(x=>x.emoji===emoji); for(const x of mine){ await g(`mutation($id:String!){ reactionDelete(id:$id){ success } }`,{id:x.id}); } console.log(JSON.stringify({removed:mine.length,commentId:last.id})); }
else { const m=await g(`mutation($in:ReactionCreateInput!){ reactionCreate(input:$in){ success reaction{ id } } }`,{in:{commentId:last.id,emoji}}); console.log(JSON.stringify({ok:m.reactionCreate.success,commentId:last.id,emoji})); }
