// cli-agents-skills-prune.test.mjs — CTL-1463 PR #3978 P1 remediation.
//
// Codex P1: cli.mjs's .agents/skills write loop only adds/overwrites files —
// it never deleted a previous generated directory whose skill was removed,
// renamed, lost its neutral opt-in, or whose pack gained a safety hook. This
// covers the fix: writeAgentsSkillsTarget must reconcile the on-disk tree
// against emittedFlatNames before writing, removing only directories that
// carry this pipeline's own generated marker.
//
// Run: bun test scripts/packaging/__tests__/cli-agents-skills-prune.test.mjs

import { describe, test, expect, afterEach } from "bun:test";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, existsSync, readdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";

import { pruneStaleAgentsSkillsDirs, writeAgentsSkillsTarget } from "../cli.mjs";
import { GENERATED_MARKER_FILENAME } from "../emitters/agents-skills.mjs";

let _tmpDirs = [];
function fixtureDir() {
  const dir = mkdtempSync(resolve(tmpdir(), "cli-prune-test-"));
  _tmpDirs.push(dir);
  return dir;
}
afterEach(() => {
  for (const dir of _tmpDirs) rmSync(dir, { recursive: true, force: true });
  _tmpDirs = [];
});

function generatedSkillDir(root, name) {
  const dir = resolve(root, name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(resolve(dir, "SKILL.md"), "---\nname: x\ndescription: x\n---\nbody\n");
  writeFileSync(resolve(dir, GENERATED_MARKER_FILENAME), JSON.stringify({ generatedBy: "catalyst-packaging" }));
  return dir;
}

describe("pruneStaleAgentsSkillsDirs", () => {
  test("absent root — returns [] without creating anything", () => {
    const root = resolve(fixtureDir(), "does-not-exist");
    expect(pruneStaleAgentsSkillsDirs(root, [])).toEqual([]);
    expect(existsSync(root)).toBe(false);
  });

  test("removes a generated dir not in emittedFlatNames; keeps one that is", () => {
    const root = fixtureDir();
    generatedSkillDir(root, "keep-me");
    generatedSkillDir(root, "stale-one");

    const pruned = pruneStaleAgentsSkillsDirs(root, ["keep-me"]);

    expect(pruned).toEqual(["stale-one"]);
    expect(existsSync(resolve(root, "keep-me"))).toBe(true);
    expect(existsSync(resolve(root, "stale-one"))).toBe(false);
  });

  test("never touches a directory that lacks the generated marker, even if absent from emittedFlatNames", () => {
    const root = fixtureDir();
    const handPlaced = resolve(root, "hand-placed");
    mkdirSync(handPlaced, { recursive: true });
    writeFileSync(resolve(handPlaced, "SKILL.md"), "not generated by us");

    const pruned = pruneStaleAgentsSkillsDirs(root, []);

    expect(pruned).toEqual([]);
    expect(existsSync(handPlaced)).toBe(true);
  });

  test("a stale dir sitting alongside a fresh emitted one: only the stale one is removed", () => {
    const root = fixtureDir();
    generatedSkillDir(root, "catalyst-dev-linearis"); // e.g. a hook-gaining skill's old bundle
    generatedSkillDir(root, "catalyst-meta-validate-frontmatter");

    const pruned = pruneStaleAgentsSkillsDirs(root, ["catalyst-meta-validate-frontmatter"]);

    expect(pruned).toEqual(["catalyst-dev-linearis"]);
    expect(readdirSync(root)).toEqual(["catalyst-meta-validate-frontmatter"]);
  });
});

function renderedPack(packId, skillId) {
  return {
    contractVersion: 1,
    packId,
    sourceRoot: `plugins/${packId}`,
    skills: [
      {
        id: skillId,
        name: skillId,
        description: "d",
        body: "# Title\n\nBody.\n",
        files: [{ relPath: "SKILL.md", bytesRef: `sha256:${"a".repeat(64)}`, content: Buffer.from("x").toString("base64") }],
        neutral: { effects: [], invocation: "auto", exposure: ["catalog"] },
      },
    ],
    agents: [],
    hooks: { present: false, entryCount: 0 },
    mcpServers: null,
  };
}

function packManifest(packId) {
  return {
    packId,
    identity: { description: "d", author: { name: "a", email: "a@b.com" }, homepage: "https://x", repository: "https://x.git", keywords: ["x"], license: "MIT" },
    distribution: { claude: { enabled: true }, codex: { enabled: true }, agentsSkills: { enabled: true } },
    skills: {},
  };
}

describe("writeAgentsSkillsTarget — end-to-end wiring of the prune-before-write fix", () => {
  test("a stale directory from a prior render is removed when a fresh render no longer emits it", () => {
    const repoRootPath = fixtureDir();
    const agentsSkillsRoot = resolve(repoRootPath, ".agents/skills");
    generatedSkillDir(agentsSkillsRoot, "catalyst-dev-linearis"); // stale: not in this render's results

    const results = [{ packId: "catalyst-meta", pack: renderedPack("catalyst-meta", "validate-frontmatter"), packManifest: packManifest("catalyst-meta") }];
    const outcome = writeAgentsSkillsTarget(repoRootPath, results, { write: true });

    expect(outcome.prunedNames).toEqual(["catalyst-dev-linearis"]);
    expect(existsSync(resolve(agentsSkillsRoot, "catalyst-dev-linearis"))).toBe(false);
    expect(existsSync(resolve(agentsSkillsRoot, "catalyst-meta-validate-frontmatter/SKILL.md"))).toBe(true);
  });

  test("dry run (write:false) prunes nothing — no filesystem mutation on a plan-only call", () => {
    const repoRootPath = fixtureDir();
    const agentsSkillsRoot = resolve(repoRootPath, ".agents/skills");
    generatedSkillDir(agentsSkillsRoot, "catalyst-dev-linearis");

    const results = [{ packId: "catalyst-meta", pack: renderedPack("catalyst-meta", "validate-frontmatter"), packManifest: packManifest("catalyst-meta") }];
    const outcome = writeAgentsSkillsTarget(repoRootPath, results, { write: false });

    expect(outcome.prunedNames).toEqual([]);
    expect(existsSync(resolve(agentsSkillsRoot, "catalyst-dev-linearis"))).toBe(true);
  });
});
