// Tests for the CTL-150 brand-v2 favicon set.
//
// The set has a single source of truth at `assets/brand-v2/favicons/`, generated by
// `assets/brand-v2/favicons/build.sh` and distributed to three consumer locations:
// repo root, `website/public/`, and `plugins/dev/scripts/orch-monitor/public/`.
//
// These tests assert the source set is complete and well-formed, and that each
// consumer location is byte-identical with the source.

import { describe, it, expect } from "bun:test";
import { existsSync, readFileSync, statSync } from "fs";
import { createHash } from "crypto";
import { join } from "path";

// __dirname → plugins/dev/scripts/orch-monitor/__tests__
// Repo root is five levels up.
const REPO_ROOT = join(__dirname, "..", "..", "..", "..", "..");
const SOURCE_DIR = join(REPO_ROOT, "assets", "brand-v2", "favicons");

function md5(path: string): string {
  return createHash("md5").update(readFileSync(path)).digest("hex");
}

// Read the first N bytes of a file as a Uint8Array (for binary header parsing).
function readBytes(path: string, n: number): Uint8Array {
  const buf = readFileSync(path);
  return new Uint8Array(buf.buffer, buf.byteOffset, Math.min(n, buf.byteLength));
}

// Parse PNG dimensions from the IHDR chunk (bytes 16-23 are width/height, big-endian u32).
function pngDimensions(path: string): { width: number; height: number } {
  const bytes = readBytes(path, 24);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  return { width: view.getUint32(16), height: view.getUint32(20) };
}

// Read the colorType byte from a PNG IHDR chunk (offset 25).
//   2 = RGB, 6 = RGBA. Used to assert apple-touch-icon has no alpha.
function pngColorType(path: string): number {
  const buf = readFileSync(path);
  return buf[25];
}

// Parse an ICO header to list embedded image sizes.
// Layout: 6-byte file header (reserved, type=1 ICO, image count u16),
// then 16-byte directory entries (width u8, height u8, ...). 0 means 256.
function icoSizes(path: string): number[] {
  const buf = readFileSync(path);
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  const reserved = view.getUint16(0, true);
  const type = view.getUint16(2, true);
  const count = view.getUint16(4, true);
  if (reserved !== 0 || type !== 1) throw new Error(`not an ICO: ${path}`);
  const sizes: number[] = [];
  for (let i = 0; i < count; i++) {
    const offset = 6 + i * 16;
    const w = buf[offset];
    sizes.push(w === 0 ? 256 : w);
  }
  return sizes.sort((a, b) => a - b);
}

describe("CTL-150 — favicon source set", () => {
  const expected = [
    "favicon.svg",
    "favicon.ico",
    "apple-touch-icon.png",
    "icon-192.png",
    "icon-512.png",
    "safari-pinned-tab.svg",
  ];

  it.each(expected)("ships %s in assets/brand-v2/favicons/", (file) => {
    expect(existsSync(join(SOURCE_DIR, file))).toBe(true);
  });

  it("favicon.svg uses currentColor and viewBox 0 0 64 64", () => {
    const svg = readFileSync(join(SOURCE_DIR, "favicon.svg"), "utf-8");
    expect(svg).toContain('viewBox="0 0 64 64"');
    expect(svg).toContain("currentColor");
  });

  it("favicon.svg has no hex color literals", () => {
    const svg = readFileSync(join(SOURCE_DIR, "favicon.svg"), "utf-8");
    expect(svg).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
  });

  it("safari-pinned-tab.svg is monochrome — no currentColor, no opacity, no stroke", () => {
    const svg = readFileSync(join(SOURCE_DIR, "safari-pinned-tab.svg"), "utf-8");
    expect(svg).toContain('viewBox="0 0 16 16"');
    expect(svg).not.toContain("currentColor");
    expect(svg).not.toMatch(/\bopacity\b/);
    expect(svg).not.toMatch(/\bstroke\b/);
    // Single fill — Safari recolors the fill, so no per-path color overrides allowed.
    const fillCount = (svg.match(/fill\s*=/g) ?? []).length;
    expect(fillCount).toBeLessThanOrEqual(1);
  });

  it("favicon.ico is multi-resolution with 16, 32, and 48 px slots", () => {
    const sizes = icoSizes(join(SOURCE_DIR, "favicon.ico"));
    expect(sizes).toEqual([16, 32, 48]);
  });

  it("apple-touch-icon.png is 180x180 with no alpha (solid background)", () => {
    const path = join(SOURCE_DIR, "apple-touch-icon.png");
    const { width, height } = pngDimensions(path);
    expect(width).toBe(180);
    expect(height).toBe(180);
    // Apple iOS composites onto its own bg awkwardly when the icon has alpha.
    expect(pngColorType(path)).toBe(2);
  });

  it("icon-192.png is exactly 192x192", () => {
    const { width, height } = pngDimensions(join(SOURCE_DIR, "icon-192.png"));
    expect(width).toBe(192);
    expect(height).toBe(192);
  });

  it("icon-512.png is exactly 512x512", () => {
    const { width, height } = pngDimensions(join(SOURCE_DIR, "icon-512.png"));
    expect(width).toBe(512);
    expect(height).toBe(512);
  });
});

describe("CTL-150 — distribution to consumer locations", () => {
  // [filename, consumer dir relative to repo root]
  const distribution: [string, string][] = [
    ["favicon.svg", "."],
    ["favicon.ico", "."],
    ["apple-touch-icon.png", "."],
    ["favicon.svg", "website/public"],
    ["favicon.ico", "website/public"],
    ["apple-touch-icon.png", "website/public"],
    ["icon-192.png", "website/public"],
    ["icon-512.png", "website/public"],
    ["safari-pinned-tab.svg", "website/public"],
    ["favicon.svg", "plugins/dev/scripts/orch-monitor/public"],
    ["favicon.ico", "plugins/dev/scripts/orch-monitor/public"],
  ];

  it.each(distribution)("%s at %s matches the source by md5", (file, dir) => {
    const sourcePath = join(SOURCE_DIR, file);
    const consumerPath = join(REPO_ROOT, dir, file);
    expect(existsSync(consumerPath)).toBe(true);
    expect(md5(consumerPath)).toBe(md5(sourcePath));
  });

  // V1 squircle leftovers — these are explicitly removed by the build script.
  it.each([
    "favicon.png",
    "website/public/favicon.png",
    "plugins/dev/scripts/orch-monitor/public/catalyst-logo.svg",
  ])("V1 leftover %s is removed", (relPath) => {
    expect(existsSync(join(REPO_ROOT, relPath))).toBe(false);
  });
});

describe("CTL-150 — build script", () => {
  it("build.sh exists and is executable", () => {
    const buildPath = join(SOURCE_DIR, "build.sh");
    expect(existsSync(buildPath)).toBe(true);
    const mode = statSync(buildPath).mode;
    expect(mode & 0o111).toBeGreaterThan(0);
  });

  it("README documents the favicon set", () => {
    const readme = readFileSync(join(SOURCE_DIR, "README.md"), "utf-8");
    for (const file of [
      "favicon.svg",
      "favicon.ico",
      "apple-touch-icon.png",
      "icon-192.png",
      "icon-512.png",
      "safari-pinned-tab.svg",
    ]) {
      expect(readme).toContain(file);
    }
  });
});
